version: '3.8'

services:
  nginx:
    build: "./requirements/nginx"
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always

  wordpress:
    build: "./requirements/wordpress"
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    environment:
      - MARIA_DB_ROOT_USER=${MARIA_DB_ROOT_USER}
      - MARIA_DB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MARIA_DB_DATABASE_NAME=${MARIA_DB_DATABASE_NAME}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_TEST_USER=${WORDPRESS_TEST_USER}
      - WORDPRESS_TEST_USER_PASSWORD=${WORDPRESS_TEST_USER_PASSWORD}
      - WORDPRESS_TEST_USER_EMAIL=${WORDPRESS_TEST_USER_EMAIL}
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build: "./requirements/mariadb"
    container_name: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MARIA_DB_ROOT_USER=${MARIA_DB_ROOT_USER}
      - MARIA_DB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - MARIA_DB_DATABASE_NAME=${MARIA_DB_DATABASE_NAME}
    networks:
      - inception
    restart: always

networks:
  inception:
